### ISSUE TITLE
fix issue with ng deploy

### ISSUE THREAD

**Issue by Carpenteri1** [Carpenteri1/Portfolio#93]
seem to get this error on ng deploy

[error] Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
    at Object.code (/Users/<username>/.repos/Portfolio/node_modules/ajv/dist/vocabularies/core/id.js:6:15)
    at keywordCode (/Users/<username>/.repos/Portfolio/node_modules/ajv/dist/compile/validate/index.js:464:13)
    at /Users/<username>/.repos/Portfolio/node_modules/ajv/dist/compile/validate/index.js:222:17
    at CodeGen.code (/Users/<username>/.repos/Portfolio/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/Users/<username>/.repos/Portfolio/node_modules/ajv/dist/compile/codegen/index.js:568:18)
    at iterateKeywords (/Users/<username>/.repos/Portfolio/node_modules/ajv/dist/compile/validate/index.js:219:9)
    at groupKeywords (/Users/<username>/.repos/Portfolio/node_modules/ajv/dist/compile/validate/index.js:208:13)
    at /Users//<username>/.repos/Portfolio/node_modules/ajv/dist/compile/validate/index.js:192:13
    at CodeGen.code (/Users/<username>/.repos/Portfolio/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/Users/<username>/.repos/Portfolio/node_modules/ajv/dist/compile/codegen/index.js:568:18)

**Comment by Carpenteri1** [comment]
Problem seems to be in ajv

**Comment by Carpenteri1** [comment]
Seems to be a problem with:

git remote add origin https://github.com/><username>/<repository>.git
npm i angular-cli-ghpages
ng deploy --base-href=/<repo-name>/

Try clear catches, remove origin, rpm packages and deploy
